### ISSUE TITLE
Tag commits according to the version of the documentation

### ISSUE THREAD

**Issue by jvleminc** [rancher/rancher-docs#1035]
## Summary

I noticed the documentation doesn't have tags and everything is maintained in master, which makes it hard to build the documentation for a certain, older version. It would be good to tag certain commits, maybe according to the Rancher versions and even create "releases" of the documentation.

**Comment by btat** [comment]
Hi @jvleminc, by building an older version of the documentation are you referring to

1. Building the documentation for commit-99 vs commit-100
2. Building the documentation set for Rancher 2.8 vs an building it for an older documentation set like Rancher 2.6

If you could expand on your use case a bit it'll help us better understand whether this is should we should consider.

**Comment by jvleminc** [comment]
Thanks for the quick answer.
Mostly, our use case is the second option you mention. 
We'd like to identify/tag the commit that constitutes the "release" of a version; sometimes we have (internal) issues with the latest commit from _main_, so we'd like to "remain" in a certain doc "version". 
We can check out a certain commit to obtain the same results, but IMHO that isn't a very clean way.

**Comment by btat** [comment]
We currently don't create tags/releases because all commits to main are published immediately and (in theory) that contains the most up-to-date and correct information, which is what we want users to use.  However, we could follow the Kubernetes docs (https://github.com/kubernetes/website/releases) by calling the tag/release an initial snapshot (and maybe adding disclaimers/notes explaining what that means). Does that work for you?

**Comment by jvleminc** [comment]
Yep, that would work very well! Thanks in advance!
