### ISSUE TITLE
[BUG] Console error being thrown 'Cannot read properties of undefined (reading 'TenantFeatures')' when landing in Rancher Docs

### ISSUE THREAD

**Issue by yonasberhe23** [rancher/rancher-docs#1249]
## Related Issues 
https://github.com/rancher/qa-tasks/issues/1289

## Summary
When navigating to Rancher Docs, a console error is thrown ('Cannot read properties of undefined (reading 'TenantFeatures'). 

Repro steps:
1. in Chrome browser, login to Rancher UI as an admin/standard user 
2. navigate to Home Page
3. scroll down to support links
4. click on 'Docs' link (https://ranchermanager.docs.rancher.com/v2.8)
5. open dev tools > console log
7. notice error > otBannerSdk.js:7 Uncaught TypeError: Cannot read properties of undefined (reading 'TenantFeatures')

Side note: This error is being caught by our e2e test automation and causing our tests to fail. 

<img width="1504" alt="Screenshot 2024-04-22 at 3 42 42 PM" src="https://github.com/rancher/rancher-docs/assets/127343932/67d7207c-fa94-4f1f-ad39-eef5145da73b">

**Comment by btat** [comment]
Adding some notes here:

- I'm not able to consistently reproduce the error.
- I can reproduce the error on Chrome/Edge in incognito/private mode by navigating to the docs site directly. I do not need to go through the Rancher UI.
- Since this is only reproducible on "first visits", I suspect it's related to the cookie consent banner that we were asked to add.
  - I also see the error on https://documentation.suse.com/.

**Comment by btat** [comment]
This was investigated in SD-155559 and concluded as no longer reproducible.
