### ISSUE TITLE
Support authentication with service account tokens

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher-docs#1373]
## Related Issues

(https://github.com/rancher/rancher/issues/22417)
https://jira.suse.com/browse/SURE-2476

## Summary
Ranchers auth proxy can now support authentication of requests that specify a Service Account token in the Authorization Bearer header

**Comment by samjustus** [comment]
@crobby to add more details

**Comment by LucasSaintarbor** [comment]
@crobby @samjustus Do have more details/screenshots you can share about this feature and what should be added to the docs? Should info about this feature live under https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/manage-clusters? 

As of 2.9, will this be the only way to enable JWT Authentication (Service Account Authentication) for a cluster?

1. Go to **Cluster Management**
2. Go to **Advanced** and select **JWT Authentication** 
3. Select cluster > click **Enable**

![Screenshot 2024-07-15 at 2 37 31 PM](https://github.com/user-attachments/assets/a072c08d-e218-4719-a8ea-45c1781ffa0f)

**Comment by crobby** [comment]
> @crobby @samjustus Do have more details/screenshots you can share about this feature and what should be added to the docs? Should info about this feature live under https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/manage-clusters?
> 
> As of 2.9, will this be the only way to enable JWT Authentication (Service Account Authentication) for a cluster?
> 
> 1. Go to **Cluster Management**
> 2. Go to **Advanced** and select **JWT Authentication**
> 3. Select cluster > click **Enable**
> 
> ![Screenshot 2024-07-15 at 2 37 31 PM](https://private-user-images.githubusercontent.com/83089978/348861963-a072c08d-e218-4719-a8ea-45c1781ffa0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NjU2NjAsIm5iZiI6MTcyMTY2NTM2MCwicGF0aCI6Ii84MzA4OTk3OC8zNDg4NjE5NjMtYTA3MmMwOGQtZTIxOC00NzE5LWE4ZWEtNDVjMTc4MWZmYTBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDE2MjI0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzOWYyMzNjMDdhYzkyNGI3YzQxYjk1MzJlYTU4YjY4MDFhMWI1ZjJlYWJkZDZiMzRhZGMxYjk2Njk3MzkxNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MFJvtpdklOrngx1PVhy1g1xhSK--UEKJ4UyGBBjCpp8)

I don't have any additional screenshots...the feature is pretty minimal UI-wise.

I'm not sure if this belongs under "new user guides".  I say that because this isn't really a basic/intro feature that would likely be of use to new users.  That being said, I'm not sure where the best fit would be.

In addition to being able to configure this through the UI, it is also possible to manually create a ClusterProxyConfig object in the target clusters namespace on the local cluster to enable/disable the feature, but I'm not sure we want/need to document that approach.

**Comment by crobby** [comment]
@LucasSaintarbor Is there any additional content you need from me for this?  Are you taking care of adding the docs?

**Comment by crobby** [comment]
A little more info/context that you may or may not have:

JWT Authentication is also known as Service Account Token Authentication. 

This feature, when enabled, lets a user set up a downstream cluster to support authentication, through Rancher, of tokens that are created for a service account that exists on a downstream cluster (those tokens are in the form of a JWT).

Prior to this feature, Rancher would reject such requests because Rancher would only support Rancher-issued tokens (which are NOT JTWs).  Some users worked-around this limitation by issuing those requests directly to the downstream cluster, rather than relying on Rancher's auth/security.  With this feature enabled, users no longer have to work-around Rancher.

A common use case for this is to enable integration of secret vault solutions (like Hashicorp Vault).  You can see the original rancher/rancher issue for more details https://github.com/rancher/rancher/issues/22417.

**Comment by martyav** [comment]
There was a child ticket associated with the Jira, which proposed updating the general FAQ page as well. Re-opened as we still need to address.

**Comment by martyav** [comment]
I can take on the task and create a PR.
