### ISSUE TITLE
Unable to set CIS profile to 1.23 for rke 1.24.x

### ISSUE THREAD

**Issue by riuvshyn** [rancher/rancher-docs#731]
**Environmental Info:**
RKE2 Version: 	v1.24.15+rke2r1

Cluster Configuration: 3 servers 3 workers

**Describe the bug:**
Documentation says that CIS 1.23 profile should be compatible with rancher provisioned RKE2 k8s 1.24.x
https://ranchermanager.docs.rancher.com/v2.7/pages-for-subheaders/rancher-hardening-guides#rke2-guides
But in fact looks like only 1.5 and 1.6 supported https://github.com/rancher/rke2/blob/v1.24.15%2Brke2r1/pkg/rke2/rke2.go#L66-L67

**Steps To Reproduce:**
set cis profile to 1.23

**Expected behavior:**
CIS profile 1.23 is set

**Actual behavior:**
rke2 server fails with error:
```
invalid value provided for --profile
```

**Additional context / logs:**
This is required to upgrade from 1.24.x to 1.25.x, as per official upgrade doc we have to disable PSP admission plugin and remove all PSPs and then upgrade to 1.25.x, currently this is impossible because PSP admission plugin is enforced by CIS 1.6...

**Comment by riuvshyn** [comment]
@brandond when I am removing `profile` from `machineGlobalConfig` it still enforces PSP admission plugin
```
I0719 14:00:02.207036       1 flags.go:64] FLAG: --enable-admission-plugins="[NodeRestriction,PodSecurityPolicy,NodeRestriction]"
```
So I guess it falls back to some default  value... 
I've tried to set it to `null` or `none` but then it fails with:
```
invalid value provided for --profile flag
```

**Comment by riuvshyn** [comment]
@brandond I've found this https://github.com/rancher/rke2/blob/v1.24.15%2Brke2r1/pkg/cli/cmds/profile_linux.go#L116
and tried to set it to `"profile": ""` 
and I am getting this message in rke2-server:
```
time="2023-07-19T14:49:12Z" level=warning msg="not running in CIS mode"
```

However `kube-apiserver-*` pods are still starting with 
```
FLAG: --enable-admission-plugins="[NodeRestriction,PodSecurityPolicy,NodeRestriction]"
```

**Comment by martyav** [comment]
From Slack:

> Someone opened an issue in RKE2 noting that the Rancher docs claim that RKE2 1.24 supports the CIS-1.23 benchmark profile, which it does not. I think the confusion comes from the fact that Rancher’s CIS benchmark chart will scan RKE2 1.24 using the cis-1.23 benchmark version, but RKE2 itself only supports configuring cis-1.5 and cis-1.6. The difference is immaterial as the actual enforced configuration is the same on the RKE2 side, but the Rancher docs do create additional confusion.

**Comment by brandond** [comment]
Please check out the docs at https://docs.rke2.io/security/pod_security_policies. The Disabling the CIS profile does not disable PSPs, it just changes the default policies that are installed to the cluster. As I mentioned above, we don't have any docs that cover completely disabling PSPs on 1.24 and replacing it with PSA. I am not entirely sure that it is even possible to completely disable it; your best bet is probably to just leave the the `global-unrestricted-psp` PSP in place and just set up your own PSA config.

**Comment by riuvshyn** [comment]
@brandond what I want to achieve right now is to disable `PodSecurityPolicy` admission plugin so that would allow me to remove my service PSPs otherwise If I will remove my service PSPs pods would be blocked to schedule.

**Comment by Martin-Weiss** [comment]
FYI - this is my workaround to "disable PSP enforcement):

(if role does not exist - in RKE2 it should)

`kubectl create clusterrole system-unrestricted-psp-role --verb use --resource podsecuritypolicies.policy --resource-name system-unrestricted-psp`

(assing right to use system-unrestricted-psp to all default service accounts)

`for NAMESPACE in $(kubectl get ns|grep -v NAME|cut -f1 -d " "); do kubectl create -n $NAMESPACE rolebinding system-unrestricted-psp-rolebinding --clusterrole system-unrestricted-psp-role --group system:serviceaccounts:$NAMESPACE; done`

Hint: -> enable PSA before that / maybe add another policy engine i.e. kubewarden - otherwise the system will be open
Hint: -> update all helm charts after this with disable PSP support to get the currently ones deleted
Hint: -> only after the helm upgrades upgrade to 1.25..
