### ISSUE TITLE
Fix Documentation for upgrade steps on a Rancher 2.6 air-gapped (originally installed and upgraded with helm template)

### ISSUE THREAD

**Issue by gunamata** [rancher/rancher-docs#982]
SURE-7154

**Comment by martyav** [comment]
@gunamata I started looking into the associated ticket. There are several references in the ticket description to using "`helm template` with the `--no-hooks` flag". I'm not familiar with how to use the `template` command. The existing commands look like this:

```bash
helm upgrade rancher ./rancher-<VERSION>.tgz \
    --flag \
    --flag \
    --flag \
```

Would this request mean simply slotting in `helm template` where `helm upgrade` is now, and including `--no-hooks` among the listed flags? Or do the code blocks need to be updated more extensively?

**Comment by martyav** [comment]
Run `helm template` with the flags already listed in the code blocks, plus the `--no-hooks` flag, then run  `kubectl apply -f` to implement the changes?

**Comment by axeal** [comment]
@martyav In summary, the issue is that any air-gapped user who installed Rancher with the `helm template` method (as was documented for Rancher <= v2.5) cannot use the `helm upgrade` method which is now the documented air-gapped method in the v2.5 - v2.8 documentation.

We are in a situation where two air-gapped upgrade methods need to be documented:

1. The `helm upgrade` method for any air-gapped user who installed Rancher with `helm install` (and not `helm template`), per the Rancher >= v2.6 air-gapped documentation (https://ranchermanager.docs.rancher.com/v2.6/getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/air-gapped-upgrades).
2. The `helm template` method for any air-gapped user who installed Rancher with `helm template` and `kubectl apply`, per the Rancher <= v2.5 air-gapped documentation (https://ranchermanager.docs.rancher.com/v2.5/getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/air-gapped-upgrades).

It would be good to call this out in the documentation, and if the `helm upgrade` method is to be recommended going forward, to provide directions on how a user can migrate from the `helm template` to `helm upgrade` method (which I think would require manually adding the helm labels and annotations to all the Rancher chart deployed resource in their Rancher cluster).

**Comment by martyav** [comment]
@axeal Thanks for the clarification. Going forward, which of the two methods would you recommend? It seems to me that `helm template` is "safer" in that users can review it before they implement changes, but are there any other hidden caveats?

**Comment by btat** [comment]
@martyav `helm upgrades` is the one to use going forward, but we'll need to add a migration path as @axeal suggested. The change to `upgrade` was needed because of bugs with `template` per https://github.com/rancher/rancher-docs/issues/808.
